---
title: "Occupational Health Analysis"
author: "Anssi Ahokas"
date: "23/08/2020"
output: 
  html_document:
    css: "styles.css"
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r warning=FALSE, include=FALSE}
## Libraries
library(tidyverse)
library(survival)
library(survminer)
library(ggplot2)
library(ggfortify)

## Theme
theme_aa <- function(){
  theme(plot.background = element_rect(fill = "#314455"),
        panel.background = element_rect(fill = "#314455"),
        )
}
```

Start with raw data! As in alustava analyysi

```{r}
data_raw <- read.csv(paste0(here::here(), "/data/2017-05-29-tyojaterveys-opendata-COMPLETE.csv"), sep = "")
meta_raw <- read.csv(paste0(here::here(), "/data/2017-05-29-tyojaterveys-metadata-LARGE.csv"), sep = "")

data <- data_raw
meta <- meta_raw
```

Because we want to research working ability we need to create proper target(s)

```{r}
## Three different targets
data$target_tyokykyHenkinen <- ifelse(data$t13 %in% c("4", "5"), 1, 0)
data$target_tyokykyFyysinen <- ifelse(data$t12 %in% c("4", "5"), 1, 0)
data$target_tyokykyArvio <- ifelse(data$t11 < 7, 1, 0)

## Combine targets
data$target_tyokyky <- ifelse(
  data$target_tyokykyFyysinen == 1 | 
  data$target_tyokykyHenkinen == 1 | 
  data$target_tyokykyArvio == 1, 1, 0)
```


```{r}
## Age group plot 
data %>% 
  select(ika) %>% 
  ggplot(aes(x = ika)) + geom_bar(stat="count", fill = "#C96567") +
  scale_x_discrete(limits = c("alle 35 vuotta", "35-44", "45-54", "yli 55")) +
  theme_aa()
```


```{r}
## Age simulation function
age_simulation <- function(x){
  if(x == "1"){
    round(runif(1, min = 24, max = 34), digits = 1)
  } else if(x == "2") {
    round(runif(1, min = 34, max = 44), digits = 1)
  } else if(x == "3") {
    round(runif(1, min = 44, max = 54), digits = 1)
  } else {
    round(runif(1, min = 54, max = 64), digits = 1)
  }
}
```


```{r}
## Number of simulations
sims <- 9

## Create a storage matrix. Each column represents one simulation
simulations <- matrix(ncol = sims, nrow = length(data$ika))

## Make simulations
for(i in 1:sims){
  simulations[,i] <- sapply(data$ika, age_simulation)
}

## The distribution plot
simulations %>% 
  as.data.frame() %>% 
  gather(key = "simulation", value = "value") %>% 
  ggplot(aes(x = value, color = simulation)) + 
  geom_density(alpha = 0.2) +
  theme_aa()
```

```{r}
data$ika_simuloitu <- sapply(data$ika, age_simulation)
```


```{r}
data <- data %>% 
  filter(vuosi > 2002) %>% #Vuosi 1997 pudettu pois toimialan vuoksi. Vuoden 1997 ja 2000 pudotettu pois etätyön vuoksi 
  filter(j20 < 6) %>% # Eli tässä otetaan pois kaikki kenellä ei ole esimiestä tai ei osaa vastata
  filter(j35 < 6) %>% # Otetaan tässä pois ne jotka eivät osaa vastata JohdonHuolenpitoon
  filter(j19 < 6) %>% # Otetaan vertaistuesta pois taas ne jotka eivät osaa sanoa 
  filter(j16b < 6) %>% # Otetaan tiimityöstä pois jotka eivät vastaa/osaa sanoa
  filter(l1a < 3) %>% # Otetaan pois jotka eivät vastaa/osaa sanoa
  select(id,
         vuosi,
         b1, #Sukupuoli
         tol2008, #Toimiala
         ika, # Otetaan mukaan ihan tarkastuksen vuoksi
         ika_simuloitu, # simuloitu ika, itse tehty, ei metaa
         j20, #esimiestuki, ei vielä muokattu, vain filtteröity
         j35, #johdonHuolenpito, ei muoktattu, vain filtteröity
         j16b, #tiimityö, ei muokattu, filtteröity
         j19, # vertaistuki
         l1a, # onko työterveyttä dummy
         target_tyokykyHenkinen,
         target_tyokykyFyysinen,
         target_tyokykyArvio,
         target_tyokyky
         ) %>% 
  mutate(j20j35 = j20 + j35) %>% # uusi muuttuja johdon huolenpidosta ja esimiestuesta. Aika vähän arvoja ääripäässä eli 8, 9.. pitäisikö yhdistää??
  mutate(j20j35j19 = j20 + j35 + j19) %>% # mukana myös vertaistuki
  mutate(j20j35mod = ifelse(j20j35 > 7, 8, j20j35)) %>% # yhdistetty j20j35 ja korvattu ääriarvot, tämä hyvä selittäjä
  mutate(j20j35j19mod = ifelse(j20j35j19 > 9, 10, j20j35j19)) # yhdistetty j20j35 ja korvattu ääriarvot, tämä hyvä selittäjä
```



```{r}
model <- survfit(Surv(ika_simuloitu, target_tyokyky) ~ j20j35mod, data = data)

ggsurvplot(model,
           data = data,
           xlim = c(35, 62),
           ylim = c(0.2, 1),
           ggtheme = theme_aa()
          )
```



